color, typo 추가
yourssu/YDS-React-old pull request #2
Opened 2021-12-30 05:31 UTC by jaewoong2

Color, Typography 추가하였습니다. 확인 부탁드립니다.

2022-02-03 12:57 UTC, dinohan reviewed
PR 제목이 color, typo 추가인 것이 내용과 안 어울리네요,
PR은 적당한 단위로 쪼개는 게 좋습니다.
- color, typo 추가.
- BoxButton 추가.
- ...
이들은 모두 다른 PR로 작성이 되었어야 할 것 같아요.

2022-02-03 12:57 UTC, dinohan commented on src/BoxButton/BoxButton.tsx
> +const Button = styled.button<ButtonProps>`
style 코드, type 정의 코드가 분리되어 있으며 보기 좋을 것 같습니다.

2022-02-03 13:20 UTC, dinohan requested changes

2022-02-03 13:20 UTC, dinohan commented on src/components/BoxButton/BoxButton.tsx
> +    <ThemeProvider>
ThemeProvider는 이렇게 쓰면 안 됩니다.
ThemeProvider는 사용처에서 넣어줘야 해요.
스토리북에서 ThemeProvider를 사용하기 위해선 preview.js 에서 ThemeProvider를 넣어주면 됩니다.
다만, emotion ThemeProvider가 storybook에서 작동하지 않는 이슈가 있으니 살펴보시면 좋겠습니다.

https://github.com/storybookjs/storybook/issues/10231

2022-02-03 13:20 UTC, dinohan commented on src/styles/theme/index.tsx
> +)
이렇게 하면, 사용처에서의 확장성을 막게 됩니다.
다크모드를 고려한다면, theme을 사용처에서 주입할 수 있도록 해야 해요.
prop에 theme을 받고, defaultTheme을 여기서 넣어주는 건 상관없을 것 같습니다.

2022-02-03 13:20 UTC, dinohan commented on src/styles/common/colors/semanticColors.ts
> +const semanticColors: { [color in type.SemanticColrs]: string } = {
나중에 다크모드가 생길 것을 고려하면 네이밍이 적절치 않습니다.
LightThemeColors 정도가 적당할 것 같네요.

2022-02-03 13:20 UTC, dinohan commented on src/stories/BoxButton.stories.tsx
> +} as ComponentMeta<typeof BoxButton>
stories 파일이 각 컴포넌트 구현 폴더 내에 있으면 보기 편할 것 같습니다.

2022-02-03 13:20 UTC, dinohan commented on src/components/Toggle/Toggle.tsx
> +        ? css`
ternary operator가 nesting되어있는 형태는 가독성을 크게 해칩니다.
이 부분 전체를 함수로 빼서, if() {return} 의 형태로 작성하는 게 좋아보여요.

2022-02-03 13:20 UTC, dinohan commented on src/components/Toggle/Toggle.tsx
> +      ? !isDisabled
Figma 정의상 isDisabled라는 prop을 쓰고 있지만, html 스펙상 semantic한 정의인 disabled를 쓰는게 더 좋을 것 같아요.
그러면 styled props가 아닌, css state를 활용해 코드를 작성할 수 있습니다.
이 경우, 성능상 이점이 있습니다.

또한, disabled, checked 같은 boolean 상태의 경우, ternary Operator로 처리하기보단,
기본 상태의 css를 정의하고, 각 상태에 따라 css를 추가해주는 형태가 좋습니다.

```plain text
// as-is
${({ isDisabeld, isSelected }) =>
  isSelected
     ? isDisabled
         ? SD : S
     : isDisabled
         ? D : A
}
// to-be
A
&:checked {
  S
}
&:disabled {
  D
}
```

2022-02-03 13:20 UTC, dinohan commented on src/components/TextField/TextField.tsx
> +    isFocused &&
이것도 input의 기본 state인 `:focus`를 활용할 수 있겠어요.

2022-02-03 13:20 UTC, dinohan commented on src/styles/common/colors/colors-type.ts
> +}
enum으로 정의한 이유가 있을까요?
type alias로 충분해 보입니다.
이 enum을 value로 사용하는 것보다, string으로 입력하고 type-checking을 하는 방식이 편해보여요.
type alias는 매번 import 해 줄 필요가 없기 때문입니다.

2022-02-08 16:54 UTC, EATSTEAK commented on src/styles/common/colors/colors-type.ts
> +}
type LogoColors = "logoBlue" | "logoYellow"
이런식으로 literal union 활용하면 좋을 것 같아요

2022-03-28 11:55 UTC, merged