아이콘 자동 생성
yourssu/YDS-React-old pull request #6
Opened 2022-03-27 16:04 UTC by EATSTEAK

* SVG 파일을 기반으로 React 아이콘 컴포넌트를 자동 생성합니다.
* `tools/generate-icons.js` 파일을 `node` 로 실행하십시오. 혹은 `yarn generate-icons` 를 실행하시면 됩니다.
* 생성된 아이콘은 `src/icons/generated` 아래에 생성되며 편리한 export 등록을 위해 `src/icon/index.ts` 에 모든 아이콘을 export 합니다.
* 아이콘은 React 의 `memo` 기능을 사용하여 재-렌더링 되지 않도록 하였고, svg element 와 동일한 속성을 갖습니다.
* Figma 에서 export 한 svg 파일을 그대로 사용하면 변환해 줍니다.
* Common 에서 사용하는 Icon naming 에 크기를 더하여 React 의 PascalCase 형태로 변환합니다. e.g) `ic_arrow_left_filled` -> `ArrowLeftFilled24Icon`
* 아이콘의 width, height, viewBox 값은 Figma 에서 export 한 값을 그대로 가져와서 사용합니다. 몇몇 아이콘의 크기가 제대로 설정되어 있지 않은 경우가 있는데, 확인하여 수정 부탁드립니다. @dinohan
* 아이콘의 fill 값은 기본값인 `#505458` 을 사용하지 않고 svg element 의 fill 값을 따라가도록 했습니다. Color System이 Merge 되면 기본 색상 값이 반영되도록 하면 좋을 것 같습니다.
* Figma에서 일부 아이콘의 component 이름이 `Frame 77` `Frame 80` 과 같이 설정되어 있습니다. 임의로 다른 크기의 이름을 가져와 수정했습니다.(`ic_plus_line`, `ic_new_line`)
* size varient 가 24 밖에 존재하지 않는 `ic_rank_*` 아이콘은 deprecated 된 것으로 가정하고 제외했습니다.
* prettier 를 통해서 포맷팅되게 했는데, 추후에 `eslint --fix` 가 된 형태로 나오도록 고쳐보겠습니다.

2022-03-27 18:47 UTC, dinohan requested changes, later dismissed
같은 아이콘에 대해 20, 24, 48 따로 생성할 필요가 없습니다. size prop을 받아서 width와 height를 넣어주는 게 합리적일 것 같네요.

2022-03-27 18:51 UTC, dinohan commented
Figma에서 export 하는데 사이즈가 다르다면 레이어 선택을 제대로 했는지 확인해보세요. svg vector 그래픽을 단순히 클릭만 하면 정확한 레이어가 안 잡힙니다.
vector를 감싸고 있는 container를 잡아야 해요.

2022-03-28 02:40 UTC, EATSTEAK commented
> 같은 아이콘에 대해 20, 24, 48 따로 생성할 필요가 없습니다. size prop을 받아서 width와 height를 넣어주는 게 합리적일 것 같네요.

Webpack 등 bundler에서 특정 크기의 icon만 번들할 수 있도록 일부러 크기별로 나눴습니다. size prop 을 추가하는 방식으로 구현했을때 특별한 이점이 있을까요?

2022-03-28 02:50 UTC, EATSTEAK commented
> Figma에서 export 하는데 사이즈가 다르다면 레이어 선택을 제대로 했는지 확인해보세요. svg vector 그래픽을 단순히 클릭만 하면 정확한 레이어가 안 잡힙니다. vector를 감싸고 있는 container를 잡아야 해요.

`Icon system_line_48/ic_x_line` 아이콘을 export 하면 width 52, height 51 크기의 svg 가 나옵니다. figma의 Inspect 상으로는 크기가 48x48 으로 잘 나오는데 얘만 이러네요. 혹시 재현 되시는지 확인 부탁드립니다.
```xml
<svg width="52" height="51" viewBox="0 0 52 51" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_4006_4786)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M13.2721 12.7279C13.8579 12.1421 14.8076 12.1421 15.3934 12.7279L38.7279 36.0624C39.3137 36.6482 39.3137 37.598 38.7279 38.1837C38.1422 38.7695 37.1924 38.7695 36.6066 38.1837L13.2721 14.8492C12.6863 14.2634 12.6863 13.3137 13.2721 12.7279Z" fill="#505458"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M38.7279 12.7279C39.3137 13.3137 39.3137 14.2634 38.7279 14.8492L15.3934 38.1837C14.8076 38.7695 13.8578 38.7695 13.2721 38.1837C12.6863 37.598 12.6863 36.6482 13.2721 36.0624L36.6066 12.7279C37.1924 12.1421 38.1421 12.1421 38.7279 12.7279Z" fill="#505458"/>
</g>
<defs>
<clipPath id="clip0_4006_4786">
<rect width="36" height="36" fill="white" transform="translate(26) rotate(45)"/>
</clipPath>
</defs>
</svg>
```

2022-04-03 16:42 UTC, merged